// servers.js

/**
 * Array of connected realms in World of Warcraft
 * Each sub-array represents a group of realms that are connected together,
 * allowing players to interact across these connected realms
 * // Example of a connected realm group
 * ["Aerie Peak", "Bronzebeard", "Blade's Edge", "Eonar", "Vek'nilash"]
 */
export const connectedRealms = [
  ["Aerie Peak", "Bronzebeard", "Blade's Edge", "Eonar", "Vek'nilash"],
  ["Agamaggan", "Bloodscalp", "Crushridge", "Emeriss", "Hakkar", "Twilight's Hammer"],
  ["Aggra (Português)", "Grim Batol", "Frostmane"],
  ["Aggramar", "Hellscream"],
  ["Ahn'Qiraj", "Balnazzar", "Boulderfist", "Chromaggus", "Daggerspine",
  "Laughing Skull", "Shattered Halls", "Sunstrider", "Talnivarr", "Trollbane"],
  ["Al'Akir", "Burning Legion", "Skullcrusher", "Xavius"],
  ["Alexstrasza", "Nethersturm", "Madmortem", "Proudmoore"],
  ["Alleria", "Rexxar"],
  ["Alonsus", "Anachronos", "Kul Tiras"],
  ["Aman'Thul", "Nazjatar", "Khaz'Goroth"],
  ["Ambossar", "Kargath", "Thrall"],
  ["Anetheron", "Festung der Stürme", "Gul'dan", "Kil'jaeden", "Nathrezim", "Rajaxx"],
  ["Anub'arak", "Dalvengyr", "Frostmourne", "Zuluhed"],
  ["Arak-arahm", "Kael'thas", "Rashgarroth", "Throk'Feroth"],
  ["Arathi", "Illidan", "Naxxramas", "Temple noir"],
  ["Arathor", "Hellfire", "Kilrogg", "Nagrand", "Runetotem"],
  ["Archimonde", "Stonemaul"],
  ["Area 52", "Sen'jin", "Un'Goro"],
  ["Arthas", "Blutkessel", "Durotan", "Kel'Thuzad", "Tirion", "Vek'lor", "Wrathbringer"],
  ["Arygos", "Khaz'goroth"],
  ["Aszune", "Shadowsong"],
  ["Auchindoun", "Dunemaul", "Jaedenar", "Sylvanas"],
  ["Azjol-Nerub", "Molten Core", "Quel'Thalas"],
  ["Azshara", "Krag'jin", "Baelgun", "Lothar"],
  ["Azuremyst", "Stormrage"],
  ["Blackmoore", "Lordaeron", "Tichondrius"],
  ["Blackscar", "Borean Tundra", "Grom", "Thermaplugg", "Booty Bay", "Deathweaver"],
  ["Bladefist", "Frostwhisper", "Zenedar", "Darksorrow", "Genjuros", "Neptulon"],
  ["Bloodfeather", "Burning Steppes", "Darkspear", "Executus", "Kor'gall",
     "Saurfang", "Shattered Hand", "Terokkar"],
  ["Bloodhoof", "Khadgar"],
  ["Bronze Dragonflight", "Nordrassil"],
  ["Burning Blade", "Drak'thul"],
  ["C'Thun", "Dun Modr"],
  ["Elune", "Varimathras"],
  ["Chants éternels", "Vol'jin"],
  ["Cho'gall", "Eldre'Thalas", "Sinstralis", "Dalaran", "Marécage de Zangar"],
  ["Colinas Pardas", "Los Errantes", "Tyrande"],
  ["Confrérie du Thorium", "Les Clairvoyants", "Les Sentinelles", "Kirin Tor",
     "Conseil des Ombres", "Culte de la Rive noire", "La Croisade écarlate"],
  ["Das Konsortium", "Das Syndikat", "Der abyssische Rat", "Die Arguswacht",
     "Die Todeskrallen", "Kult der Verdammten", "Die ewige Wacht", "Die Silberne Hand"],
  ["Deathwing", "Dragonblight", "Ghostlands", "Karazhan", "Lightning's Blade",
     "The Maelstrom"],
  ["Deepholm", "Galakrond", "Razuvious"],
  ["Darkmoon Faire", "Defias Brotherhood", "Earthen Ring", "Ravenholdt",
     "Scarshield Legion", "Sporeggar", "The Venture Co"],
  ["Dentarg", "Tarren Mill"],
  ["Destromath", "Gorgonnash", "Mannoroth", "Nefarian", "Nera'thor"],
  ["Dethecus", "Mug'thol", "Onyxia", "Terrordar", "Theradras"],
  ["Die Nachtwache", "Forscherliga", "Todeswache", "Zirkel des Cenarius",
     "Der Mithrilorden", "Der Rat von Dalaran"],
  ["Doomhammer", "Menethil", "Turalyon"],
  ["Dragonmaw", "Haomarush", "Spinebreaker", "Stormreaver", "Vashj"],
  ["Drek'Thar", "Uldaman", "Eitrigg", "Krasus"],
  ["Dun Morogh", "Norgannon"],
  ["Echsenkessel", "Mal'Ganis", "Taerar", "Blackhand"],
  ["Emerald Dream", "Terenas"],
  ["Exodar", "Minahonda"],
  ["Garona", "Ner'zhul", "Sargeras"],
  ["Garrosh", "Nozdormu", "Perenolde", "Shattrath", "Teldrassil"],
  ["Gilneas", "Nefarian"],
  ["Goldrinn", "Greymane", "Lich King"],
  ["Lightbringer", "Mazrigos"],
  ["Malfurion", "Malygos"],
  ["Malorne", "Ysera"],
  ["Medivh", "Suramar"],
  ["Moonglade", "Steamwheedle Cartel", "The Sha'tar"],
  ["Sanguino", "Shen'dralar", "Uldum", "Zul'jin"],
  ["Stormscale", "Winterhuf"],
  ["Thunderhorn", "Wildhammer"]
];

export const notConnectedRealms = [
  "Aegwynn",
  "Antonidas",
  "Argent Dawn",
  "Ashenvale",
  "Azuregos",
  "Blackrock",
  "Chamber of Aspects",
  "Deathguard",
  "Die Aldor",
  "Draenor",
  "Eredar",
  "Eversong",
  "Fordragon",
  "Frostwolf",
  "Howling Fjord",
  "Hyjal",
  "Kazzak",
  "Khaz Modan",
  "Magtheridon",
  "Nemesis",
  "Outland",
  "Pozzo dell'Eternità",
  "Ragnaros",
  "Ravencrest",
  "Silvermoon",
  "Soulflayer",
  "Twisting Nether",
  "Ulduar",
  "Ysondre"
];

// Function to get a random server
export function getRandomServer() {
  const allRealms = [...connectedRealms, ...notConnectedRealms];
  return allRealms[Math.floor(Math.random() * allRealms.length)];
}
